name: Backend CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: starter/backend

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          pip install flask==2.2.3
          pip install flask-cors==3.0.10
          pip install werkzeug==2.2.3
          pip install pytest==7.2.1

      - name: Run tests
        run: pytest -v